### PR TITLE
Show link to build scan on the Build page

### PR DESCRIPTION
**Pull request by wolfs**
This changes adds the link to the [Build Scan](https://scans.gradle.com/) to the build page, if it has been created. For creating a build scan for the current Gradle build see the instructions [here](https://scans.gradle.com/setup/step-1).

### CODE REVIEW

**Comment by wolfs** [comment]
@gezerk @jhinrichsen @gboissinot : Are you maintaining this plugin? Could you have a look at this PR? I requested becoming the maintainer: https://groups.google.com/forum/#!topic/jenkinsci-dev/XLUqvvZ15Tg

Would that be OK with you?

**Comment by gezerk** [comment]
Hi Guys,
Just finished moving family cross country.  I will merge this PR tomorrow.

**Comment by gezerk** [comment]
Congratulations on becoming a committer.  Thanks very much for merging this.

**Comment by wolfs** [comment]
@gezerk : Thanks! What is your current involvement with this plugin? Should we co-maintain it?

I did not see your earlier comment about you wanting to merge this tomorrow. I hope I did not step on your toes.

Please add yourself to the list of developers.

**Comment by gezerk** [comment]
HI Stefan,
We are heavy consumers of the plugin.  No one was actively maintaining it
for a long time so I tried to pick it up.  I was able to merge a couple of
pull requests, but I never managed to release.  I would enjoy
co-maintaining, but I don’t want to get in your way.  Lets try and if it
isn’t working I will step away.
I was glad you got the merge done.  You definitely did not step on my
toes.  Thanks for coming on board!

**Comment by wolfs** [comment]
Hi @gezerk,

thank you for your response! I am currently not consuming this plugin since I am working at Gradle and we are using Teamcity. But I am a long time Jenkins committer (since 2009) and have some interest that the Gradle integration in Jenkins works well. So I think maintaining this together makes sense since you will have more feel for what a user of the plugin needs while I should have more insight what makes sense from the Gradle side of things.
Going forward my plan for the next weeks was to work through the remaining pull requests and have a look at the open bugs. I am still somewhat limited with respect to the time I can invest in working on the plugin so let's have a look how this works out.

**Pull request merged**
