### PR TITLE
Small Code Improvements

### PR DESCRIPTION
**Pull request by darxriggs**

### CODE REVIEW

**Comment by darxriggs** [comment]
@jvz, I extracted the patterns and added some more improvements.

**Comment by darxriggs** [comment]
@wolfs could you please have a look at this?

**Comment by wolfs** [comment]
@darxriggs Thank you for the PR. It looks good and I merged it.

How you found the things you improved? Some IDEA warnings? Can those things maybe found automatically?

Do you plan any follow up work now that the simple code improvements are in?

**Comment by darxriggs** [comment]
Some improvements have been found via IDEA: Analyze -> Inspect Code...
But most improvements are the result of a manual review.
And yes, I was waiting for this pull request to get merged, to create another one...

**Pull request merged**
