### PR TITLE
Do not try to serialize GradleInstallation over Remoting

### PR DESCRIPTION
**Pull request by jglick**
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.

### CODE REVIEW

**Comment by wolfs** [comment]
@jglick Is this something I should merge?

**Comment by jglick** [comment]
Yes, assuming of course you do not see any flaws in my refactoring. (Not sure if there is test coverage for this.)

**Comment by wolfs** [comment]
@jglick Thank you for the contribution. Is there any urgency in publishing a new version of the plugin including the change?

**Comment by jglick** [comment]
> Is there any urgency in publishing a new version of the plugin including the change?

I would not say “urgency” exactly but users of Gradle installations on agents using Jenkins weeklies will get stack traces dumped in their logs until you release this.

When you do, please: https://github.com/jenkinsci/jep/edit/master/jep/228/compatibility.adoc

**Comment by wolfs** [comment]
I released 1.37.1 including these changes.

**Pull request merged**
