### PR TITLE
Replace Guava usages with native Java Platform functionality

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by wolfs** [comment]
@basil Thank you for your pull request!

What is the motivation for replacing the Guava usages?

**Comment by basil** [comment]
> What is the motivation for replacing the Guava usages?

See [JEP-233](https://github.com/jenkinsci/jep/blob/master/jep/233/README.adoc).

**Review by alecharp — APPROVED** [review]

**Review by raul-arabaolaza — APPROVED** [review]

**Review by olamy — APPROVED** [review]

**Comment by alecharp** [comment]
@wolfs do you think you can integrate this PR and release the plugin? Thanks.

**Review by wolfs — APPROVED** [review]
LGTM!

**Comment by wolfs** [comment]
@basil Thank you again for this PR. It will be included in the next plugin release.

**Pull request merged**
