### PR TITLE
[JENKINS-40004] Add plugin description to POM

### PR DESCRIPTION
**Pull request by varyvol**
[JENKINS-40004](https://issues.jenkins-ci.org/browse/JENKINS-40004)

@reviewbybees @wolfs

### CODE REVIEW

**Comment by rsandell** [comment]
The description differs from the current excerpt in [index](https://github.com/jenkinsci/gradle-plugin/blob/master/src/main/resources/index.jelly) and [wiki](https://wiki.jenkins-ci.org/display/JENKINS/Gradle+Plugin)

**Comment by varyvol** [comment]
It matches with the one in the wiki, under the Description section. Besides, it look more generic and user-friendly to me. What do you think?

**Comment by wolfs** [comment]
I like the generic description - this allows for hosting more functionality at a later point.

**Comment by wolfs** [comment]
@varyvol Are you going to work further on this or is this done by the @reviewbybees side?

**Comment by wolfs** [comment]
@varyvol @rsandell Anything more from your side?

**Comment by varyvol** [comment]
@wolfs sorry I was on holidays. With generic description you mean the currently proposed one or which one?

**Comment by wolfs** [comment]
The proposed one. Probably the `Support` should be lower case.

**Comment by varyvol** [comment]
@wolfs agree. Done.

**Comment by recena** [comment]
🐝

**Pull request merged**
