### PR TITLE
chore: Migrate build from Maven to Gradle

### PR DESCRIPTION
**Pull request by jhinrichsen**
This is a dupe of PR #10, which is from 2012 and not auto-mergable

### CODE REVIEW

**Comment by jhinrichsen** [comment]
The above error stems from the CI system that expects a Maven pom. To switch the CI build from Maven to Gradle, we need to request a different Jenkins Template in the "Jenkins Developers" Google group.

https://groups.google.com/forum/#!topic/jenkinsci-dev/YKJ5W6ClHwo

**Comment by rodrigc** [comment]
@jhinrichsen: in your branch *jhinrichsen/gradle-plugin* repo, can you do
```
git push -f origin master
```

to force the Jenkins server to rebuild your branch?
The admins changed this job to use gradle: http://lists.jenkins-ci.org/pipermail/jenkins-infra/2016-May/000701.html

**Comment by jhinrichsen** [comment]
Yes, i can and will so as soon as I have this Prio #1 issue off my desk.

Thanks for your help!

Schönen Gruß 

Jochen

**Comment by rodrigc** [comment]
@jhinrichsen Can you do this in the next few days?

**Pull request merged**
