### PR TITLE
Reference the master doc in the Release Drafter configuration

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Just tried to check whether it is an encoding issue, does not look so

### CODE REVIEW

**Comment by wolfs** [comment]
@oleg-nenashev Shall I merge this PR?

**Comment by oleg-nenashev** [comment]
Not sure. This PR is not really helpful, it it rather a mere attempt to retrigger the build with GitHub encodings. But merging will not hurt either

https://github.com/toolmantim/release-drafter/issues/301 will likely help to triage the issue

**Comment by oleg-nenashev** [comment]
I suggest merging it to see whether it starts working.
https://github.com/jenkinsci/acceptance-test-harness now generates changelogs, so something was solved

**Comment by oleg-nenashev** [comment]
No idea :(

**Pull request merged**
