### PR TITLE
Convert Plugin to be compatible with Jenkins pipeline

### PR DESCRIPTION
**Pull request by funtastix**
- DryRun was removed for this purpose and SimpleBuildStep implemented instead
- Simple usage example: "gradle tasks: 'clean assembleDebug', useWrapper: true"
- Works with Snippet Generator (which adds additional/unnecessary parameters)
- This enables gradle (wrappers) to be used easily cross-platform without scripts needed

### CODE REVIEW

**Comment by jvz** [comment]
Thanks for the contribution! Can you fix the tests?

**Comment by funtastix** [comment]
I will look into them. There seems to be additional tests running as all test had passed on my build machine.

**Comment by jvz** [comment]
The test failures appear to be on Windows only, so that could be part of the problem.

**Comment by funtastix** [comment]
This is what is confusing as I build on windows. I will hopefully figure it out.

**Comment by funtastix** [comment]
@jvz I tracked the failures down to a parameter passing ending in '\'. I don't understand what this needs to look like and how my changes would have affected those  tests. The parameter encoding is done via Jenkins until classes. I will try to get a comparison with and without my commits. It may be a good idea to add a new parameter test: Param="XYZ\"

**Comment by jvz** [comment]
Almost sounds like the test failure might be unrelated then?

**Comment by wolfs** [comment]
@funtastix I'll be closing the PR, given that there hasn't been any activity. Is the PR still interesting? If yes, please open a new one based on current `main`. Thank you!

**Pull request closed without merging**
