### PR TITLE
[JENKINS-29916] Installer data not always downloaded

### PR DESCRIPTION
**Pull request by andresrc**
See [JENKINS-29916](https://issues.jenkins-ci.org/browse/JENKINS-29916).

Downstream of https://github.com/jenkinsci/gradle-plugin/pull/29

Relevant commit is https://github.com/jenkinsci/gradle-plugin/commit/8e623684fb226814573bb28095b41d3ea85cf8e8

@reviewbybees

### CODE REVIEW

**Comment by wolfs** [comment]
Thank you for your pull request.

This PR does not compile - could you please fix that? It also lacks integration tests.

**Comment by andresrc** [comment]
Yes, I have to revisit the work I did in this plugin, the transition to a gradle build caught me in the middle. I will pick it up as soon as possible.

Thanks

**Comment by wolfs** [comment]
Hi @andresrc,

do you have any idea when you will have time to continue with this work? If it will not be any time soon I would prefer to close this PR.

**Comment by wolfs** [comment]
Hi @andresrc,

I didn't hear back from you since 2 months now so I am closing this. If you still want to work in this consider reopening this PR.
Thanks for your time and your PR.

Regards,
Stefan

**Pull request closed without merging**
