### PR TITLE
Fix Jenkins war download URLs

### PR DESCRIPTION
**Pull request by alextu**
Looks like download URLs are broken, switched to working ones in this PR.

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
```

### CODE REVIEW

**Comment by alextu** [comment]
ah thanks for notifying, although I still get 404 for `https://get.jenkins.io/war/latest/jenkins.war` and `https://get.jenkins.io/war-stable/latest/jenkins.war`. What are the correct "https://get.jenkins.io URLs" to get the latest and latest lts without having to know the exact version upfront ?

**Comment by lemeurherve** [comment]
Hello @alextu, that's the correct way, just it's not working at the moment.

See this help desk issue to follow its resolution: https://github.com/jenkins-infra/helpdesk/issues/3894#issuecomment-1884578927

**Comment by dduportal** [comment]
> ah thanks for notifying, although I still get 404 for `https://get.jenkins.io/war/latest/jenkins.war` and `https://get.jenkins.io/war-stable/latest/jenkins.war`. What are the correct "https://get.jenkins.io URLs" to get the latest and latest lts without having to know the exact version upfront ?

The URL is good: it is an ongoing issue we are currently facing (ref. https://github.com/jenkins-infra/helpdesk/issues/3894#issuecomment-1884578927).

However I realize the servuce `updates.jenkins.io` provides the resolution of the "latest" version in a different way than the `get.jenkins.io` with its `latest` (first one uses custom Apache logic generated by the update center while the second relies on symlinks in the storage).
The latter one is subject to numerous issues (the one I linked earlier but other) so I believe this PR should be merge for you to unblock you.

I'll notice the whole infra team about the `/current/latest` feature for update center for future operations.

Sorry for the noise.

**Comment by alextu** [comment]
Thanks for the explanation and good luck with the ongoing issue!

**Comment by lemeurherve** [comment]
BTW, @alextu next time you see this kind of issue don't hesitate to open a help desk ticket at https://github.com/jenkins-infra/helpdesk/issues/new/choose

**Comment by dduportal** [comment]
Notes:

- The URL `https://get.jenkins.io/war/latest/jenkins.war` is now properly redirected to `https://archives.jenkins.io/war/latest/jenkins.war` since https://github.com/jenkins-infra/helpdesk/issues/3894#issuecomment-1884651604
- As per https://github.com/jenkins-infra/helpdesk/issues/3860, there might be other issues with the `latest` representation within get.jenkins.io, which further justifies the PR here.

**Pull request merged**
